import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
// import Title from "@/components/Title";
// import { ThreeDMarqueeDemo } from "@/components/ThreeDMarquee";
// import { ImagesSliderDemo } from "@/components/ui/ImagesSliderDemo";
// import Footer from "@/components/Footer";

const turnkey = localFont({
  src: [
    {
      path: "../../public/poppin/relative-faux.ttf",
      style: "normal",
      weight: "700",
    },
    {
      path: "../../public/poppin/relative-medium.ttf",
      style: "normal",
      weight: "600",
    },
    {
      path: "../../public/poppin/relative-regular.ttf",
      style: "normal",
      weight: "500",
    },
  ],
  variable: "--turnkey-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={`${turnkey.className}`}>
          <main>
            <Header />
            {/* < ImagesSliderDemo/> */}
            {/* <ThreeDMarqueeDemo/> */}
            {/* <Title /> */}
            {children}
            <Footer />
          </main>

          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
